<a href="https://colab.research.google.com/github/mayankraj25/CasualPortfolio/blob/main/Untitled8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
from warnings import filterwarnings
filterwarnings('ignore')
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "countries of the world.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "fernandol/countries-of-the-world",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)
df.head()

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service
0,Afghanistan,ASIA (EX. NEAR EAST),31056997,647500,"48,0","0,00","23,06","163,07",700.0,"36,0","3,2","12,13","0,22","87,65",1,"46,6","20,34","0,38","0,24","0,38"
1,Albania,EASTERN EUROPE,3581655,28748,"124,6","1,26","-4,93","21,52",4500.0,"86,5","71,2","21,09","4,42","74,49",3,"15,11","5,22","0,232","0,188","0,579"
2,Algeria,NORTHERN AFRICA,32930091,2381740,"13,8","0,04","-0,39",31,6000.0,"70,0","78,1","3,22","0,25","96,53",1,"17,14","4,61","0,101","0,6","0,298"
3,American Samoa,OCEANIA,57794,199,"290,4","58,29","-20,71","9,27",8000.0,"97,0","259,5",10,15,75,2,"22,46","3,27",NaN,NaN,NaN
4,Andorra,WESTERN EUROPE,71201,468,"152,1","0,00","6,6","4,05",19000.0,"100,0","497,2","2,22",0,"97,78",3,"8,71","6,25",NaN,NaN,NaN

In [18]:
import pandas as pd
df.isnull().sum()
df = df.replace(',', '', regex=True)
df = df.apply(pd.to_numeric, errors='coerce')

In [19]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Country']=le.fit_transform(df['Country'])
df['Region']=le.fit_transform(df['Region'])

In [20]:
df.head()

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service
0,0,0,31056997,647500,480,0,2306.0,16307.0,700.0,360.0,32.0,1213.0,22.0,8765.0,1.0,466.0,2034.0,38.0,24.0,38.0
1,1,3,3581655,28748,1246,126,-493.0,2152.0,4500.0,865.0,712.0,2109.0,442.0,7449.0,3.0,1511.0,522.0,232.0,188.0,579.0
2,2,6,32930091,2381740,138,4,-39.0,31.0,6000.0,700.0,781.0,322.0,25.0,9653.0,1.0,1714.0,461.0,101.0,6.0,298.0
3,3,8,57794,199,2904,5829,-2071.0,927.0,8000.0,970.0,2595.0,10.0,15.0,75.0,2.0,2246.0,327.0,NaN,NaN,NaN
4,4,10,71201,468,1521,0,66.0,405.0,19000.0,1000.0,4972.0,222.0,0.0,9778.0,3.0,871.0,625.0,NaN,NaN,NaN

In [24]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(strategy='mean')
df=imputer.fit_transform(df)

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
df=scaler.fit_transform(df)